name: Main
on:

  push:
    branches:
      - main
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    enviornment:
    steps:
      - name: product metrics
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}